services:
  nginx:
    image: local-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-logs:/var/log/nginx
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    container_name: python_app
    ports:
      - 8000:8000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
